tinyMCE.addI18n('cro.advanced',{
style_select:"Stilovi",
font_size:"Veli\u010dina fonta",
fontdefault:"Vrsta fonta",
block:"Format",
paragraph:"Paragraf",
div:"Div",
address:"Adresa",
pre:"Oblikovano",
h1:"Naslov 1",
h2:"Naslov 2",
h3:"Naslov 3",
h4:"Naslov 4",
h5:"Naslov 5",
h6:"Naslov 6",
blockquote:"Citat",
code:"Kod",
samp:"Primjer koda",
dt:"Definicija pojma ",
dd:"Opis definicije",
bold_desc:"Podebljano (Ctrl+B)",
italic_desc:"Uko\u0161eno (Ctrl+I)",
underline_desc:"Podcrtano (Ctrl+U)",
striketrough_desc:"Precrtano",
justifyleft_desc:"Poravnaj lijevo",
justifycenter_desc:"Centriraj",
justifyright_desc:"Poravnaj desno",
justifyfull_desc:"Poravnaj obostrano",
bullist_desc:"Nenumerirana lista",
numlist_desc:"Numerirana lista",
outdent_desc:"Uvuci",
indent_desc:"Izvuci",
undo_desc:"Poni\u0161ti (Ctrl+Z)",
redo_desc:"Ponovi (Ctrl+Y)",
link_desc:"Umetni/uredi link",
unlink_desc:"Poni\u0161ti link",
image_desc:"Umetni/uredi sliku",
cleanup_desc:"Po\u010disti neuredan kod",
code_desc:"Uredi HTML izvor",
sub_desc:"Indeks",
sup_desc:"Eksponent",
hr_desc:"Umetni vodoravnu crtu",
removeformat_desc:"Poni\u0161ti oblikovanje",
custom1_desc:"Vlastiti opis ovdje",
forecolor_desc:"Odaberite boju teksta",
backcolor_desc:"Odaberite boju pozadine",
charmap_desc:"Umetni vlastiti znak",
visualaid_desc:"Vodilice/nevidljivi elementi",
anchor_desc:"Umetni/uredi sidro",
cut_desc:"Izre\u017ei",
copy_desc:"Kopiraj",
paste_desc:"Zalijepi",
image_props_desc:"Svojstva slike",
newdocument_desc:"Novi dokument",
help_desc:"Pomo\u0107",
blockquote_desc:"Citiraj",
clipboard_msg:"Kopiraj/Izre\u017ei/Zalijepi nije dostupno u Mozilla i Firefox preglednicima. Vi\u0161e informacija?",
path:"Putanja",
newdocument:"Jeste li sigurni da \u017eelite izbrisati cijeli sadr\u017eaj?",
toolbar_focus:"Prije\u0111i na alatnu traku - Alt+Q, prije\u0111i na ure\u0111iva\u010d - Alt-Z, prije\u0111i na putanju elementa - Alt-X",
more_colors:"Vi\u0161e boja",

// Accessibility Strings
shortcuts_desc:'Pomo\u0107 pristupa\u010dnosti',
help_shortcut:'. Pritisnite ALT F10 za alatnu traku. Pritisnite ALT 0 za pomo\u0107.',
rich_text_area:"Dio za formatirani tekst",
toolbar:"Alatna traka"
});
