tinyMCE.addI18n('cro.table_dlg',{
general_tab:"Op\u0107e",
advanced_tab:"Napredno",
general_props:"Op\u0107a svojstva",
advanced_props:"Napredna svojstva",
rowtype:"Redak u dijelu tablice",
title:"Umetni/uredi tablicu",
width:"\u0160irina",
height:"Visina",
cols:"Stupaca",
rows:"Redaka",
cellspacing:"Razmak \u0107elija",
cellpadding:"Dopuna \u0107elije",
border:"Obrub",
align:"Poravnavanje",
align_default:"Osnovno",
align_left:"Lijevo",
align_right:"Desno",
align_middle:"Sredina",
row_title:"Svojstva retka",
cell_title:"Svojstva \u0107elije",
cell_type:"Tip \u0107elije",
valign:"Okomito poravnavanje",
align_top:"Vrh",
align_bottom:"Dno",
bordercolor:"Boja obruba",
bgcolor:"Boja pozadine",
merge_cells_title:"Spoji \u0107elije",
id:"Id",
style:"Stil",
langdir:"Smjer jezika",
langcode:"Kod jezika",
mime:"MIME tip",
ltr:"S lijeva na desno",
rtl:"S desna na lijevo",
bgimage:"Slika pozadine",
summary:"Sa\u017eetak",
td:"Podatkovna",
th:"Zaglavlje",
cell_cell:"Primjeni na odabranu \u0107eliju",
cell_row:"Primjeni na sve \u0107elije u retku",
cell_col:"Primjeni na sve \u0107elije u stupcu",
cell_all:"Primjeni na sve \u0107elije u tablici",
row_row:"Primjeni na odabrani redak",
row_odd:"Primjeni na neparne retke u tablici",
row_even:"Primjeni na parne retke u tablici",
row_all:"Primjeni na sve retke u tablici",
thead:"Zaglavlje tablice",
tbody:"Tijelo tablice",
tfoot:"Podno\u017eje tablice",
scope:"Domet",
rowgroup:"Grupa redaka",
colgroup:"Grupa stupaca",
col_limit:"Pre\u0161li ste maksimalan broj stupaca ({$cols}).",
row_limit:"Pre\u0161li ste maksimalan broj redaka ({$rows}).",
cell_limit:"Pre\u0161li ste maksimalan broj \u0107elija ({$cells}).",
missing_scope:"Jeste li sigurni da \u017eelite nastaviti bez da ste odredili podru\u010dje zaglavlja za ovu tablicu. Bez toga postoji mogu\u0107nost da \u0107e neki korisnici sa pote\u0161ko\u0107ama te\u0161ko razumjeti sadr\u017eaj ili podatke va\u0161e tablice.",
caption:"Opis tablice",
frame:"Okvir",
frame_none:"bez okvira",
frame_groups:"grupe",
frame_rows:"redovi",
frame_cols:"stupci",
frame_all:"sve",
rules:"Linije",
rules_void:"prazno",
rules_above:"iznad",
rules_below:"ispod",
rules_hsides:"gornja i doljnja",
rules_lhs:"samo lijevo",
rules_rhs:"samo desno",
rules_vsides:"lijevo i desno",
rules_box:"sve strane",
rules_border:"okvir"
});