tinyMCE.addI18n('cro.media_dlg',{
title:"Dodaj / uredi ugra\u0111enu multimediju",
general:"Op\u0107e",
advanced:"Napredno",
file:"Datoteka/URL",
list:"Lista",
size:"Dimenzije",
preview:"Predpregled",
constrain_proportions:"Zadr\u017ei proporcije",
type:"Tip",
id:"Id",
name:"Ime",
class_name:"Klasa",
vspace:"V-Razmak",
hspace:"H-Razmak",
play:"Automatska izvedba",
loop:"Kru\u017ena izvedba",
menu:"Prila\u017ei izbornik",
quality:"Kvaliteta",
scale:"Veli\u010dina",
align:"Poravnanje",
salign:"SAlign",
wmode:"WMode",
bgcolor:"Pozadina",
base:"Baza",
flashvars:"Flashvars",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"Cache",
hidden:"Skriveno",
controller:"Kontroler",
kioskmode:"Kiosk mod",
playeveryframe:"Prila\u017ei svaki frame",
targetcache:"Cache meta",
correction:"Bez ispravka",
enablejavascript:"Omogu\u0107i JavaScript",
starttime:"Vrijeme po\u010detka",
endtime:"Vrijeme zavr\u0161etka",
href:"Href (lokacija)",
qtsrcchokespeed:"Brzina kliza\u010da",
target:"Meta",
volume:"Ja\u010dina zvuka",
autostart:"Automatsko pokretanje",
enabled:"Omogu\u0107eno",
fullscreen:"Cijeli ekran",
invokeurls:"Dozovi URLove",
mute:"Isklju\u010di zvuk",
stretchtofit:"Ra\u0161iri da stane",
windowlessvideo:"Video bez prozora",
balance:"Balans",
baseurl:"Osnovni URL",
captioningid:"Id titlova",
currentmarker:"Trenutni marker",
currentposition:"Trenutna pozicija",
defaultframe:"Osnovni okvir",
playcount:"Broj izvedbi",
rate:"Brzina",
uimode:"UI Mod",
flash_options:"Flash opcije",
qt_options:"Quicktime opcije",
wmp_options:"Windows media player opcije",
rmp_options:"Real media player opcije",
shockwave_options:"Shockwave opcije",
autogotourl:"Automatski idi na URL",
center:"Sredina",
imagestatus:"Status slike",
maintainaspect:"Zadr\u017ei aspekt",
nojava:"Bez jave",
prefetch:"Prethodno punjenje",
shuffle:"Mije\u0161ani redoslijed",
console:"Konzola",
numloop:"Broj prikazivanja",
controls:"Kontrole",
scriptcallbacks:"Poziv (callback) skripte",
swstretchstyle:"Stil \u0161irenja",
swstretchhalign:"Ra\u0161iri vodoravno",
swstretchvalign:"Ra\u0161iri okomito",
sound:"Zvuk",
progress:"Napredak",
qtsrc:"QT Src (Izvor)",
qt_stream_warn:"Izvori rtsp streamanja trebali bi biti dodani u QT Src polje u naprednom tabu.\nTako\u0111er, trebali bi dodati i obi\u010dnu verziju u Src polje...",
align_top:"Gore",
align_right:"Desno",
align_bottom:"Dno",
align_left:"Lijevo",
align_center:"Sredina",
align_top_left:"Gore lijevo",
align_top_right:"Gore desno",
align_bottom_left:"Dolje lijevo",
align_bottom_right:"Dolje desno",
flv_options:"Flash video opcije",
flv_scalemode:"Mod razmera",
flv_buffer:"Buffer",
flv_starttime:"Vrijeme po\u010detka",
flv_defaultvolume:"Osnovna ja\u010dina zvuka",
flv_hiddengui:"Skriveni GUI",
flv_autostart:"Automatsko pokretanje",
flv_loop:"Kru\u017ena izvedba",
flv_showscalemodes:"Prikaži modove razmjera",
flv_smoothvideo:"Glatki video",
flv_jscallback:"JS povratni poziv",
html5_video_options:"HTML5 Video Opcije",
html5_audio_options:"HTML5 Audio Opcije",
altsource1:"Alternativni izvor 1",
altsource2:"Alternativni izvor 2",
preload:"Predhodno u\u010ditavanje",
poster:"Poster",
preload_none:"Nemoj predhodno u\u010ditavati",
preload_metadata:"Predhodno u\u010ditaj videos meta podatke",
preload_auto:"Neka korisnikov preglednik odluèi",
source:"Izvor"
});