tinyMCE.addI18n('cro.advanced_dlg',{
about_title:"O TinyMCE",
about_general:"O programu",
about_help:"Pomo\u0107",
about_license:"Licenca",
about_plugins:"Dodaci",
about_plugin:"Dodatak",
about_author:"Autor",
about_version:"Verzija",
about_loaded:"Postoje\u0107i dodaci",
anchor_title:"Umetni/uredi sidro",
anchor_name:"Ime sidra",
anchor_invalid:"Molimo unesite ispravno ime sidra.",
code_title:"HTML ure\u0111iva\u010d",
code_wordwrap:"Omatanje teksta",
colorpicker_title:"Izbor boje",
colorpicker_picker_tab:"Odabir",
colorpicker_picker_title:"Odabir boje",
colorpicker_palette_tab:"Paleta",
colorpicker_palette_title:"Paleta boja",
colorpicker_named_tab:"Imenovano",
colorpicker_named_title:"Imenovane boje",
colorpicker_color:"Boja:",
colorpicker_name:"Naziv:",
charmap_title:"Odaberite znak",
image_title:"Umetni/uredi sliku",
image_src:"URL slike",
image_alt:"Opis slike",
image_list:"Lista slika",
image_border:"Obrub",
image_dimensions:"Dimenzije",
image_vspace:"Okomiti razmak",
image_hspace:"Vodoravni razmak",
image_align:"Poravnavanje",
image_align_baseline:"Osnovna linija",
image_align_top:"Na vrh",
image_align_middle:"Na sredinu",
image_align_bottom:"Na dno",
image_align_texttop:"Na vrh teksta",
image_align_textbottom:"Na dno teksta",
image_align_left:"Na lijevo",
image_align_right:"Na desno",
link_title:"Umetni/uredi link",
link_url:"URL linka",
link_target:"Meta",
link_target_same:"Otvori link u istom prozoru",
link_target_blank:"Otvori link u novom prozoru",
link_titlefield:"Naslov",
link_is_email:"URL koji ste unijeli izgleda kao e-mail adresa, \u017eelite li dodati potrebni mailto: prefiks?",
link_is_external:"URL koji ste unijeli izgleda kao vanjski link, \u017eelite li dodati potrebni http:// prefiks?",
link_list:"Lista linkova",
accessibility_help:"Pomo\u0107 pristupa\u010dnosti",
accessibility_usage_title:"Op\u0107enita uporaba"
});