tinyMCE.addI18n('cro.fullpage_dlg',{
title:"Svojstva dokumenta",
meta_tab:"Op\u0107e",
appearance_tab:"Izgled",
advanced_tab:"Napredno",
meta_props:"Meta informacije",
langprops:"Jezik i kodiranje",
meta_title:"Naslov",
meta_keywords:"Klju\u010dne rije\u010di",
meta_description:"Opis",
meta_robots:"Roboti",
doctypes:"Doctype",
langcode:"Kod jezika",
langdir:"Smjer jezika",
ltr:"S lijeva na desno",
rtl:"S desna na lijevo",
xml_pi:"XML deklaracija",
encoding:"Kodiranje znakova",
appearance_bgprops:"Svojstva pozadine",
appearance_marginprops:"Margine",
appearance_linkprops:"Boje linka",
appearance_textprops:"Svojstva teksta",
bgcolor:"Boja pozadine",
bgimage:"Pozadinska slika",
left_margin:"Lijeva margina",
right_margin:"Desna margina",
top_margin:"Gornja margina",
bottom_margin:"Donja margina",
text_color:"Boja teksta",
font_size:"Veli\u010dina fonta",
font_face:"Font",
link_color:"Boja linka",
hover_color:"Boja linka ispod mi\u0161a",
visited_color:"Boja posje\u0107enog linka",
active_color:"Boja aktivnog linka",
textcolor:"Boja",
fontsize:"Veli\u010dina fonta",
fontface:"Skupina fonta",
meta_index_follow:"Indeksiraj i slijedi linkove",
meta_index_nofollow:"Indeksiraj i ne slijedi linkove",
meta_noindex_follow:"Ne indeksiraj i slijedi linkove",
meta_noindex_nofollow:"Ne indeksiraj i ne slijedi linkove",
appearance_style:"CSS i svojstva stila",
stylesheet:"CSS",
style:"Stil",
author:"Autor",
copyright:"Autorska prava",
add:"Dodaj novi element",
remove:"Ukloni odabrani element",
moveup:"Pomakni odabrani element prema gore",
movedown:"Pomakni odabrani element prema dolje",
head_elements:"Elementi zaglavlja",
info:"Informacije",
add_title:"Element naslova",
add_meta:"Meta element",
add_script:"Element skripte",
add_style:"Element stila",
add_link:"Element linka",
add_base:"Osnovni element",
add_comment:"Komentar",
title_element:"Element naslova",
script_element:"Element skripte",
style_element:"Element stila",
base_element:"Osnovni element",
link_element:"Element linka",
meta_element:"Meta element",
comment_element:"Komentar",
src:"Src",
language:"Jezik",
href:"Href",
target:"Cilj",
type:"Tip",
charset:"Skup znakova",
defer:"Odgoda",
media:"Media",
properties:"Svojstva",
name:"Ime",
value:"Vrijednost",
content:"Sadr\u017eaj",
rel:"Rel",
rev:"Rev",
hreflang:"Href jezik",
general_props:"Op\u0107e",
advanced_props:"Napredno"
});