tinyMCE.addI18n('cro.style_dlg',{
title:"Uredi CSS Stil",
apply:"Primjeni",
text_tab:"Tekst",
background_tab:"Pozadina",
block_tab:"Blok",
box_tab:"Okvir",
border_tab:"Obrub",
list_tab:"Lista",
positioning_tab:"Pozicioniranje",
text_props:"Tekst",
text_font:"Font",
text_size:"Veli\u010dina",
text_weight:"Te\u017eina",
text_style:"Stil",
text_variant:"Varijanta",
text_lineheight:"Visina linije",
text_case:"Velika / mala slova",
text_color:"Boja",
text_decoration:"Ukras (Decoration)",
text_overline:"Nadcrtano",
text_underline:"Podcrtano",
text_striketrough:"Precrtano",
text_blink:"Treperavo",
text_none:"ni\u0161ta",
background_color:"Pozadinska boja",
background_image:"Pozadinska slika",
background_repeat:"Ponavljanje",
background_attachment:"Privitak",
background_hpos:"Vodoravna pozicija",
background_vpos:"Okomita pozicija",
block_wordspacing:"Razmak izme\u0111u rije\u010di",
block_letterspacing:"Razmak izme\u0111u slova",
block_vertical_alignment:"Okomito poravnanje",
block_text_align:"Pozicioniranje teksta",
block_text_indent:"Uvu\u010deni tekst",
block_whitespace:"Razmak (Whitespace)",
block_display:"Prikaz (Display)",
box_width:"\u0160irina",
box_height:"Visina",
box_float:"Plutajuæe",
box_clear:"Oèisti",
padding:"Ispunjenje (Padding)",
same:"Isto za sve",
top:"Vrh",
right:"Desno",
bottom:"Dno",
left:"Lijevo",
margin:"Margine",
style:"Stil",
width:"\u0160irina",
height:"Visina",
color:"Boja",
list_type:"Tip",
bullet_image:"Bullet slika",
position:"Pozicija (Position)",
positioning_type:"Tip",
visibility:"Vidljivost (Visibility)",
zindex:"Z-index",
overflow:"Prelijevanje (Overflow)",
placement:"Polo\u017eaj",
clip:"Obre\u017ei (clip)",
text:"Tekst",
background:"Pozadina",
block:"Blok",
box:"Okvir",
border:"Obrub",
list:"Lista",
position:"Pozicija"
});