tinyMCE.addI18n('cro.advlink_dlg',{
title:"Umetni/uredi link",
url:"URL link",
target:"Meta",
titlefield:"Naslov",
is_email:"URL koji ste unijeli izgleda kao e-mail adresa, \u017eelite li dodati potrebni mailto: prefiks?",
is_external:"URL koji ste unijeli izgleda kao vanjski link, \u017eelite li dodati potrebni http:// prefiks?",
list:"Lista linkova",
general_tab:"Op\u0107e",
popup_tab:"Popup",
events_tab:"Doga\u0111aj",
advanced_tab:"Napredno",
general_props:"Osnovna svojstva",
popup_props:"Svojstva popup prozora",
event_props:"Doga\u0111aji",
advanced_props:"Napredna svojstva",
popup_opts:"Opcije",
anchor_names:"Sidra",
target_same:"Otovori u ovom prozoru / okviru",
target_parent:"Otvori u izvornom prozoru / okvir",
target_top:"Otvori u gornjem okviru (zamjenjuje sve okvire) (_top)",
target_blank:"Otvori u novom prozoru",
popup:"Javascript popup",
popup_url:"Popup URL",
popup_name:"Ime prozora",
popup_return:"Umetni 'return false'",
popup_scrollbars:"Poka\u017ei kliza\u010de",
popup_statusbar:"Poka\u017ei statusnu traku",
popup_toolbar:"Poka\u017ei alatne trake",
popup_menubar:"Poka\u017ei izbornik",
popup_location:"Poka\u017ei traku lokacije",
popup_resizable:"Prozor promjenjive veli\u010dine",
popup_dependent:"Ovisan (samo za Mozilla/Firefox)",
popup_size:"Veli\u010dina",
width:"\u0160irina",
height:"Visina",
popup_position:"Pozicija (X/Y)",
id:"Id",
style:"Stil",
classes:"Klase",
target_name:"Ciljno ime",
langdir:"Smjer jezika",
target_langcode:"Ciljni jezik",
langcode:"Kod jezika",
encoding:"Kodiranje znakova",
mime:"MIME tip",
rel:"Odnos stranice prema cilju",
rev:"Odnos cilja prema stranici",
tabindex:"Indeks kartice",
accesskey:"Pristupni kljuè",
ltr:"S lijeva na desno",
rtl:"S desna na lijevo",
link_list:"Lista linkova"
});