tinyMCE.addI18n('cro.advimage_dlg',{
tab_general:"Op\u0107e",
tab_appearance:"Izgled",
tab_advanced:"Napredno",
general:"Op\u0107e",
title:"Naslov",
preview:"Predprikaz",
constrain_proportions:"Zadr\u017ei proporcije",
langdir:"Smjer jezika",
langcode:"Kod jezika",
long_desc:"Poveznica dugog opisa",
style:"Stil",
classes:"Klase",
ltr:"S lijeva na desno",
rtl:"S desna na lijevo",
id:"Id",
map:"Karta slike",
swap_image:"Izmjenjiva slika",
alt_image:"Alternativna slika",
mouseover:"za prelazak mi\u0161a preko slike",
mouseout:"za izlazak mi\u0161a van slike",
misc:"Razno",
example_img:"Predprikaz slike",
missing_alt:"Jeste li sigurni da \u017eelite izostaviti opis slike? Slika mo\u017ee biti nedostupna ljudima s pote\u0161ko\u0107ama ili onima koji koriste preglednike bez prikaza slika.",
dialog_title:"Umetni/uredi sliku",
src:"URL slike",
alt:"Opis slike",
list:"Lista slika",
border:"Obrub",
dimensions:"Dimenzije",
width:"\u0160irina",
height:"Visina",
vspace:"Okomiti razmak",
hspace:"Vodoravni razmak",
align:"Poravnavanje",
align_baseline:"Osnovna linija",
align_top:"Na vrh",
align_middle:"Na sredinu",
align_bottom:"Na dno",
align_texttop:"Na vrh teksta",
align_textbottom:"Na dno teksta",
align_left:"Na lijevo",
align_right:"Na desno",
image_list:"Lista slika"
});